ID,nome,descricao
1,Paris,"Cidade do amor e da luz"
2,"Nova York","A cidade que nunca dorme"
3,Tóquio,"Metrópole moderna com tradiçõe"
4,Roma,"Cidade eterna com rica históri"
5,Sydney,"Cidade à beira-mar com a Opera"
6,"Rio de Janeiro","Cidade maravilhosa com praias "
7,Cairo,"Cidade dos Faraós e das pirâmi"
8,Bangkok,"Capital vibrante da Tailândia"
9,Barcelona,"Arquitetura única de Gaudí"
10,"Cidade do Cabo","Cidade na ponta sul da África"
11,Dubai,"Cidade dos arranha-céus e do l"
12,Berlim,"Cidade histórica com arte e cu"
13,Pequim,"Capital da China com a Cidade "
14,Londres,"Cidade cosmopolita com atraçõe"
15,Sidney,"Cidade na Austrália com a Sydn"
16,Amsterdã,"Cidade dos canais e cultura li"
17,Marrakech,"Cidade marroquina com mercados"
18,"Machu Picchu","Antiga cidade inca nas montanh"
19,Viena,"Capital austríaca com arquitet"
20,Toronto,"Cidade canadense diversificada"
21,Seul,"Capital da Coreia do Sul com t"
22,"Buenos Aires","Cidade argentina com cultura e"
23,Praga,"Cidade checa com arquitetura m"
24,Pequim,"Capital chinesa com uma longa "
25,Havana,"Capital de Cuba com carros vin"
26,Dublin,"Capital da Irlanda com pubs an"
27,Florença,"Cidade italiana com arte renas"
28,Atenas,"Capital grega com monumentos a"
29,Bangalore,"Cidade tecnológica na Índia"
30,Casablanca,"Cidade marroquina com uma mist"
